/* The following code was generated by JFlex 1.4.3 on 7/11/23 23:25 */

package codigo;
import static codigo.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 7/11/23 23:25 from the specification file
 * <tt>src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\2\17\1\50\1\0\2\17\22\0\1\17\6\0\1\5\1\51"+
    "\1\53\2\0\1\17\1\52\1\16\1\47\1\11\1\6\6\14\2\2"+
    "\7\0\1\24\1\4\1\33\1\25\1\34\1\45\1\46\1\43\1\31"+
    "\1\41\1\1\1\30\1\21\1\32\1\22\1\40\1\1\1\35\1\26"+
    "\1\37\1\27\1\23\1\44\1\36\1\1\1\42\4\0\1\1\1\0"+
    "\1\10\1\3\1\10\1\15\2\10\1\1\1\7\4\1\1\20\1\1"+
    "\1\13\6\1\1\20\1\1\1\12\2\1\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\2\1\1\2\2\1\3"+
    "\2\2\1\1\2\4\17\2\1\4\1\1\1\0\1\5"+
    "\1\0\1\5\1\2\4\0\1\5\2\0\1\6\2\2"+
    "\1\7\30\2\1\10\1\2\1\11\1\12\1\13\1\14"+
    "\1\2\2\0\1\15\1\16\1\6\1\17\2\0\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\2\1\31\1\32\2\2\1\33\1\34\1\35\1\36"+
    "\1\37\1\2\1\40\1\41\1\42\1\43\1\44\3\2"+
    "\1\45\1\2\1\46\1\2\1\47\1\50\1\51\1\2"+
    "\1\52\1\0\1\53\2\2\1\54\2\2\1\55\1\56"+
    "\1\57\1\60\1\61\1\62\1\63\1\3\1\64\1\65"+
    "\1\66\1\67\1\70\1\71\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\334\0\u0108\0\u0134"+
    "\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c\0\u0268\0\u0294"+
    "\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\u039c\0\u03c8\0\u03f4"+
    "\0\u0420\0\u044c\0\u0478\0\u04a4\0\u04d0\0\u04fc\0\u0528\0\u0554"+
    "\0\u0580\0\54\0\u05ac\0\130\0\u05d8\0\u0604\0\u0630\0\u065c"+
    "\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0210\0\u0738\0\u0764\0\130"+
    "\0\u0790\0\u07bc\0\u07e8\0\u0814\0\u0840\0\u086c\0\u0898\0\u08c4"+
    "\0\u08f0\0\u091c\0\u0948\0\u0974\0\u09a0\0\u09cc\0\u09f8\0\u0a24"+
    "\0\u0a50\0\u0a7c\0\u0aa8\0\u0ad4\0\u0b00\0\u0b2c\0\u0b58\0\u0b84"+
    "\0\130\0\u0bb0\0\130\0\130\0\130\0\130\0\u0bdc\0\u0c08"+
    "\0\u0c34\0\130\0\130\0\54\0\54\0\u0c60\0\u0c8c\0\u0cb8"+
    "\0\130\0\u0160\0\130\0\130\0\u0160\0\130\0\130\0\130"+
    "\0\u0ce4\0\130\0\130\0\u0d10\0\u0d3c\0\130\0\130\0\130"+
    "\0\130\0\u0d68\0\u0d94\0\130\0\130\0\130\0\u0dc0\0\130"+
    "\0\u0dec\0\u0e18\0\u0e44\0\u0e70\0\u0e9c\0\130\0\u0ec8\0\130"+
    "\0\130\0\130\0\u0ef4\0\130\0\u0f20\0\54\0\u0f4c\0\u0f78"+
    "\0\130\0\u0fa4\0\u0fd0\0\u0ffc\0\130\0\130\0\130\0\130"+
    "\0\130\0\u1028\0\54\0\130\0\130\0\130\0\130\0\130"+
    "\0\130\0\130";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\4\1\10"+
    "\1\11\1\12\1\3\1\13\1\4\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\3\1\22\1\23\1\24\1\3"+
    "\1\25\1\26\1\27\1\30\1\11\1\31\1\32\1\33"+
    "\1\34\1\35\1\3\1\36\1\3\1\11\1\3\1\37"+
    "\1\0\1\40\2\2\55\0\4\3\1\0\11\3\1\0"+
    "\27\3\7\0\1\4\2\41\1\0\1\4\1\42\1\41"+
    "\1\4\1\42\1\0\1\4\1\41\6\0\2\41\5\0"+
    "\2\41\1\0\1\42\4\0\1\42\1\0\1\41\7\0"+
    "\1\3\3\11\1\43\1\11\1\44\2\11\1\44\1\3"+
    "\2\11\1\3\1\0\4\3\2\11\5\3\2\11\1\3"+
    "\1\44\4\3\1\44\1\3\1\11\1\3\6\0\1\3"+
    "\3\11\1\43\1\11\1\44\2\11\1\44\1\3\2\11"+
    "\1\3\1\0\4\3\2\11\1\45\4\3\2\11\1\3"+
    "\1\44\4\3\1\44\1\3\1\11\1\3\7\0\1\46"+
    "\3\0\1\47\2\0\1\47\2\0\1\47\40\0\4\3"+
    "\1\50\11\3\1\0\27\3\6\0\1\3\3\11\1\0"+
    "\1\11\1\44\2\11\1\44\1\3\2\11\1\3\1\0"+
    "\4\3\2\11\5\3\2\11\1\3\1\44\4\3\1\44"+
    "\1\3\1\11\1\3\7\0\1\12\2\51\1\0\1\12"+
    "\1\42\1\51\1\12\1\52\1\0\1\12\1\51\6\0"+
    "\2\51\5\0\2\51\1\0\1\52\4\0\1\42\1\0"+
    "\1\51\7\0\4\3\1\53\11\3\1\0\27\3\6\0"+
    "\1\3\3\11\1\54\1\11\1\44\2\11\1\44\1\3"+
    "\2\11\1\3\1\0\4\3\2\11\5\3\2\11\1\3"+
    "\1\44\4\3\1\44\1\3\1\11\1\3\7\0\1\55"+
    "\3\0\1\55\2\0\1\55\2\0\1\55\56\0\2\16"+
    "\34\0\4\3\1\0\11\3\1\16\1\17\26\3\6\0"+
    "\4\3\1\0\11\3\1\0\2\3\1\56\4\3\1\57"+
    "\17\3\6\0\4\3\1\53\11\3\1\0\15\3\1\60"+
    "\11\3\6\0\1\3\3\11\1\0\1\11\1\44\2\11"+
    "\1\44\1\3\2\11\1\3\1\0\4\3\1\11\1\61"+
    "\4\3\1\62\2\11\1\3\1\44\4\3\1\44\1\3"+
    "\1\11\1\3\6\0\1\3\3\11\1\54\1\11\1\44"+
    "\2\11\1\44\1\3\2\11\1\3\1\0\4\3\2\11"+
    "\3\3\1\63\1\3\1\11\1\64\1\3\1\44\4\3"+
    "\1\44\1\3\1\11\1\3\6\0\4\3\1\0\11\3"+
    "\1\0\4\3\1\65\2\3\1\66\7\3\1\67\3\3"+
    "\1\70\3\3\6\0\4\3\1\0\11\3\1\0\2\3"+
    "\1\71\11\3\1\72\12\3\6\0\4\3\1\0\11\3"+
    "\1\0\12\3\1\73\14\3\6\0\4\3\1\0\11\3"+
    "\1\0\2\3\1\74\24\3\6\0\1\3\3\11\1\0"+
    "\1\11\1\44\2\11\1\44\1\3\2\11\1\3\1\0"+
    "\1\3\1\75\2\3\1\76\1\11\2\3\1\77\2\3"+
    "\2\11\1\3\1\44\4\3\1\44\1\3\1\11\1\3"+
    "\6\0\4\3\1\0\11\3\1\0\2\3\1\100\11\3"+
    "\1\101\12\3\6\0\4\3\1\0\11\3\1\0\2\3"+
    "\1\102\5\3\1\103\2\3\1\104\13\3\6\0\4\3"+
    "\1\0\11\3\1\0\14\3\1\105\12\3\6\0\4\3"+
    "\1\0\11\3\1\0\2\3\1\106\4\3\1\107\17\3"+
    "\6\0\4\3\1\0\11\3\1\0\1\3\1\110\6\3"+
    "\1\111\1\3\1\112\1\113\1\114\5\3\1\115\3\3"+
    "\1\116\6\0\4\3\1\50\11\3\1\0\10\3\1\117"+
    "\16\3\5\0\50\37\1\0\3\37\52\0\1\120\3\0"+
    "\3\41\1\0\1\41\1\42\2\41\1\42\1\0\2\41"+
    "\6\0\2\41\5\0\2\41\1\0\1\42\4\0\1\42"+
    "\1\0\1\41\14\0\1\121\2\0\1\121\43\0\4\3"+
    "\1\0\11\3\1\0\15\3\1\122\7\3\1\123\1\3"+
    "\7\0\1\46\2\0\1\124\1\46\2\0\1\46\2\0"+
    "\1\46\41\0\1\46\2\0\1\125\1\47\2\0\1\47"+
    "\2\0\1\47\41\0\3\126\1\0\1\126\1\0\2\126"+
    "\2\0\2\126\6\0\2\126\5\0\2\126\10\0\1\126"+
    "\10\0\3\51\1\0\1\51\1\42\2\51\1\52\1\0"+
    "\2\51\6\0\2\51\5\0\2\51\1\0\1\52\4\0"+
    "\1\42\1\0\1\51\10\0\3\52\1\0\1\52\1\0"+
    "\2\52\2\0\2\52\6\0\2\52\5\0\2\52\10\0"+
    "\1\52\14\0\1\127\2\0\1\127\2\0\1\127\41\0"+
    "\1\46\3\0\1\46\2\0\1\46\2\0\1\46\40\0"+
    "\4\3\1\0\11\3\1\0\3\3\1\130\23\3\6\0"+
    "\4\3\1\0\11\3\1\0\10\3\1\131\16\3\6\0"+
    "\1\3\3\11\1\0\1\11\1\44\2\11\1\44\1\3"+
    "\2\11\1\3\1\0\4\3\1\11\1\132\5\3\2\11"+
    "\1\3\1\44\4\3\1\44\1\3\1\11\1\3\6\0"+
    "\4\3\1\0\11\3\1\0\5\3\1\133\21\3\6\0"+
    "\4\3\1\0\11\3\1\0\3\3\1\134\23\3\6\0"+
    "\1\3\3\11\1\0\1\11\1\44\2\11\1\44\1\3"+
    "\2\11\1\3\1\0\4\3\2\11\5\3\1\135\1\11"+
    "\1\3\1\44\4\3\1\44\1\3\1\11\1\3\6\0"+
    "\4\3\1\0\11\3\1\0\10\3\1\136\4\3\1\137"+
    "\11\3\6\0\3\3\1\140\1\0\11\3\1\0\27\3"+
    "\6\0\4\3\1\0\11\3\1\0\2\3\1\141\6\3"+
    "\1\142\15\3\6\0\4\3\1\0\11\3\1\0\10\3"+
    "\1\136\4\3\1\143\11\3\6\0\4\3\1\0\11\3"+
    "\1\0\2\3\1\144\2\3\1\145\21\3\6\0\4\3"+
    "\1\0\11\3\1\0\4\3\1\146\22\3\6\0\4\3"+
    "\1\0\11\3\1\0\13\3\1\147\13\3\6\0\4\3"+
    "\1\0\11\3\1\0\17\3\1\150\1\151\6\3\6\0"+
    "\4\3\1\0\11\3\1\0\20\3\1\152\6\3\6\0"+
    "\1\3\3\11\1\0\1\11\1\44\2\11\1\44\1\3"+
    "\2\11\1\3\1\0\4\3\2\11\2\3\1\153\2\3"+
    "\2\11\1\3\1\44\4\3\1\44\1\3\1\11\1\3"+
    "\6\0\4\3\1\0\11\3\1\0\11\3\1\154\15\3"+
    "\6\0\4\3\1\0\11\3\1\0\10\3\1\155\4\3"+
    "\1\156\11\3\6\0\4\3\1\0\11\3\1\0\17\3"+
    "\1\157\7\3\6\0\4\3\1\0\11\3\1\0\15\3"+
    "\1\160\11\3\6\0\4\3\1\0\11\3\1\0\4\3"+
    "\1\161\22\3\6\0\4\3\1\0\11\3\1\0\23\3"+
    "\1\162\3\3\6\0\4\3\1\0\11\3\1\0\6\3"+
    "\1\163\20\3\6\0\4\3\1\0\11\3\1\0\20\3"+
    "\1\164\6\3\6\0\4\3\1\0\11\3\1\0\6\3"+
    "\1\165\20\3\6\0\4\3\1\0\11\3\1\0\20\3"+
    "\1\166\6\3\6\0\4\3\1\0\11\3\1\0\10\3"+
    "\1\167\2\3\1\170\1\171\5\3\1\172\3\3\1\173"+
    "\6\0\4\3\1\0\11\3\1\0\17\3\1\174\7\3"+
    "\7\0\1\175\3\0\1\175\2\0\1\175\2\0\1\175"+
    "\44\0\1\176\1\121\2\0\1\121\44\0\3\126\1\42"+
    "\1\126\1\0\2\126\2\0\2\126\6\0\2\126\5\0"+
    "\2\126\10\0\1\126\13\0\1\125\1\127\2\0\1\127"+
    "\2\0\1\127\40\0\4\3\1\0\11\3\1\0\6\3"+
    "\1\177\20\3\6\0\4\3\1\0\11\3\1\0\6\3"+
    "\1\200\20\3\6\0\4\3\1\0\11\3\1\0\20\3"+
    "\1\201\6\3\6\0\4\3\1\0\11\3\1\0\6\3"+
    "\1\202\20\3\6\0\4\3\1\0\11\3\1\0\6\3"+
    "\1\203\20\3\6\0\4\3\1\0\11\3\1\0\10\3"+
    "\1\204\16\3\6\0\4\3\1\0\11\3\1\0\25\3"+
    "\1\205\1\3\6\0\4\3\1\0\11\3\1\0\17\3"+
    "\1\206\7\3\6\0\4\3\1\0\11\3\1\0\26\3"+
    "\1\207\6\0\4\3\1\0\11\3\1\0\17\3\1\210"+
    "\7\3\6\0\4\3\1\0\11\3\1\0\25\3\1\211"+
    "\1\3\6\0\4\3\1\0\11\3\1\0\23\3\1\212"+
    "\3\3\6\0\4\3\1\0\11\3\1\0\14\3\1\116"+
    "\12\3\6\0\4\3\1\0\11\3\1\0\14\3\1\111"+
    "\12\3\7\0\1\175\3\0\1\175\2\0\1\175\2\0"+
    "\1\175\36\0\1\213\1\0\3\3\1\214\1\0\11\3"+
    "\1\0\24\3\1\215\2\3\6\0\3\3\1\216\1\0"+
    "\11\3\1\0\27\3\6\0\3\3\1\217\1\0\11\3"+
    "\1\0\27\3\6\0\3\3\1\220\1\0\11\3\1\0"+
    "\27\3\6\0\4\3\1\0\11\3\1\0\25\3\1\221"+
    "\1\3\6\0\4\3\1\0\11\3\1\0\25\3\1\222"+
    "\1\3\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4180];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\36\1\1\0\1\11\1\0\2\1\4\0"+
    "\1\1\2\0\43\1\2\0\2\1\2\11\2\0\45\1"+
    "\1\0\1\11\14\1\1\11\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
   public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 134) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 39: 
          { lexeme=yytext(); return JNC;
          }
        case 59: break;
        case 31: 
          { lexeme=yytext(); return CMP;
          }
        case 60: break;
        case 2: 
          { lexeme=yytext(); return Identificador;
          }
        case 61: break;
        case 56: 
          { lexeme=yytext(); return CMPSB;
          }
        case 62: break;
        case 25: 
          { lexeme=yytext(); return STI;
          }
        case 63: break;
        case 52: 
          { lexeme=yytext(); return MOVSB;
          }
        case 64: break;
        case 47: 
          { lexeme=yytext(); return XLAT;
          }
        case 65: break;
        case 6: 
          { lexeme=yytext(); return NumeroDecimalCustom;
          }
        case 66: break;
        case 37: 
          { lexeme=yytext(); return POP;
          }
        case 67: break;
        case 18: 
          { lexeme=yytext(); return ADD;
          }
        case 68: break;
        case 14: 
          { lexeme=yytext(); return BSF;
          }
        case 69: break;
        case 4: 
          { /*Ignorar*/
          }
        case 70: break;
        case 57: 
          { lexeme=yytext(); return CALLF;
          }
        case 71: break;
        case 55: 
          { lexeme=yytext(); return LODSB;
          }
        case 72: break;
        case 24: 
          { lexeme=yytext(); return SUB;
          }
        case 73: break;
        case 9: 
          { lexeme=yytext(); return JC;
          }
        case 74: break;
        case 49: 
          { lexeme=yytext(); return TEST;
          }
        case 75: break;
        case 46: 
          { lexeme=yytext(); return RETF;
          }
        case 76: break;
        case 33: 
          { lexeme=yytext(); return ROL;
          }
        case 77: break;
        case 53: 
          { lexeme=yytext(); return MOVSW;
          }
        case 78: break;
        case 13: 
          { lexeme=yytext(); return BSR;
          }
        case 79: break;
        case 34: 
          { lexeme=yytext(); return ROR;
          }
        case 80: break;
        case 8: 
          { lexeme=yytext(); return JL;
          }
        case 81: break;
        case 30: 
          { lexeme=yytext(); return NOP;
          }
        case 82: break;
        case 44: 
          { lexeme=yytext(); return LOOP;
          }
        case 83: break;
        case 15: 
          { lexeme=yytext(); return NumeroOctal;
          }
        case 84: break;
        case 23: 
          { lexeme=yytext(); return SAR;
          }
        case 85: break;
        case 50: 
          { lexeme=yytext(); return POPF;
          }
        case 86: break;
        case 43: 
          { lexeme=yytext(); return NumeroBinario;
          }
        case 87: break;
        case 40: 
          { lexeme=yytext(); return JNE;
          }
        case 88: break;
        case 3: 
          { lexeme=yytext(); return Numero;
          }
        case 89: break;
        case 32: 
          { lexeme=yytext(); return CLI;
          }
        case 90: break;
        case 22: 
          { lexeme=yytext(); return SHL;
          }
        case 91: break;
        case 17: 
          { lexeme=yytext(); return MUL;
          }
        case 92: break;
        case 41: 
          { lexeme=yytext(); return JNZ;
          }
        case 93: break;
        case 26: 
          { lexeme=yytext(); return SHR;
          }
        case 94: break;
        case 27: 
          { lexeme=yytext(); return LEA;
          }
        case 95: break;
        case 10: 
          { lexeme=yytext(); return JE;
          }
        case 96: break;
        case 21: 
          { lexeme=yytext(); return DEC;
          }
        case 97: break;
        case 28: 
          { lexeme=yytext(); return INC;
          }
        case 98: break;
        case 5: 
          { lexeme=yytext(); return NumeroHexadecimal;
          }
        case 99: break;
        case 45: 
          { lexeme=yytext(); return CALL;
          }
        case 100: break;
        case 11: 
          { lexeme=yytext(); return JZ;
          }
        case 101: break;
        case 58: 
          { lexeme=yytext(); return PUSHF;
          }
        case 102: break;
        case 36: 
          { lexeme=yytext(); return XOR;
          }
        case 103: break;
        case 7: 
          { lexeme=yytext(); return OR;
          }
        case 104: break;
        case 35: 
          { lexeme=yytext(); return RET;
          }
        case 105: break;
        case 51: 
          { lexeme=yytext(); return PUSH;
          }
        case 106: break;
        case 1: 
          { return ERROR;
          }
        case 107: break;
        case 48: 
          { lexeme=yytext(); return XCHG;
          }
        case 108: break;
        case 42: 
          { lexeme=yytext(); return HLT;
          }
        case 109: break;
        case 38: 
          { lexeme=yytext(); return JMP;
          }
        case 110: break;
        case 12: 
          { lexeme=yytext(); return JG;
          }
        case 111: break;
        case 20: 
          { lexeme=yytext(); return DIV;
          }
        case 112: break;
        case 16: 
          { lexeme=yytext(); return MOV;
          }
        case 113: break;
        case 54: 
          { lexeme=yytext(); return STOSB;
          }
        case 114: break;
        case 19: 
          { lexeme=yytext(); return AND;
          }
        case 115: break;
        case 29: 
          { lexeme=yytext(); return NOT;
          }
        case 116: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
