
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 22 13:11:42 PET 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_c = 57;
  public static final int Parentesis_a = 56;
  public static final int BSR = 35;
  public static final int Llave_c = 59;
  public static final int MOVSB = 26;
  public static final int Llave_a = 58;
  public static final int JEQ = 51;
  public static final int CMPSB = 44;
  public static final int Linea = 2;
  public static final int Coma = 60;
  public static final int LEA = 25;
  public static final int BSF = 34;
  public static final int TEST = 28;
  public static final int Section_data = 65;
  public static final int XCHG = 38;
  public static final int NumeroBinario = 68;
  public static final int ROR = 33;
  public static final int CLI = 43;
  public static final int ROL = 32;
  public static final int Int = 55;
  public static final int POP = 24;
  public static final int SUB = 6;
  public static final int STOSB = 46;
  public static final int POPF = 37;
  public static final int LOOP = 47;
  public static final int SHR = 30;
  public static final int NOT = 14;
  public static final int MOV = 4;
  public static final int NOP = 40;
  public static final int SHL = 29;
  public static final int ERROR = 73;
  public static final int DEC = 10;
  public static final int Global = 62;
  public static final int STI = 42;
  public static final int MUL = 7;
  public static final int SAR = 31;
  public static final int NumeroHexadecimal = 69;
  public static final int Section = 63;
  public static final int PUSHF = 36;
  public static final int Comilla_s = 61;
  public static final int JZ = 19;
  public static final int JNZ = 20;
  public static final int ADD = 5;
  public static final int DIV = 8;
  public static final int PUSH = 23;
  public static final int JL = 49;
  public static final int JG = 48;
  public static final int JE = 17;
  public static final int JC = 50;
  public static final int EOF = 0;
  public static final int Section_bss = 66;
  public static final int JNE = 18;
  public static final int NumeroOctal = 70;
  public static final int Section_text = 64;
  public static final int JNC = 52;
  public static final int Numero = 72;
  public static final int INC = 9;
  public static final int OR = 12;
  public static final int error = 1;
  public static final int JMP = 16;
  public static final int RET = 22;
  public static final int LODSB = 45;
  public static final int Identificador = 67;
  public static final int Etiquetas = 3;
  public static final int NumeroDecimal = 71;
  public static final int MOVSW = 27;
  public static final int XLAT = 39;
  public static final int AND = 11;
  public static final int HLT = 41;
  public static final int RETF = 54;
  public static final int CALL = 21;
  public static final int CMP = 15;
  public static final int XOR = 13;
  public static final int CALLF = 53;
}

