
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 10 19:22:15 PET 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CALLF = 52;
  public static final int SHR = 29;
  public static final int JNZ = 19;
  public static final int JL = 48;
  public static final int NumeroOctal = 64;
  public static final int Coma = 58;
  public static final int JEQ = 50;
  public static final int Llave_c = 57;
  public static final int NumeroHexadecimal = 63;
  public static final int Llave_a = 56;
  public static final int SHL = 28;
  public static final int JG = 47;
  public static final int RET = 21;
  public static final int POP = 23;
  public static final int XCHG = 37;
  public static final int JE = 16;
  public static final int JC = 49;
  public static final int PUSHF = 35;
  public static final int PUSH = 22;
  public static final int XOR = 12;
  public static final int STI = 41;
  public static final int Etiquetas = 2;
  public static final int CMPSB = 43;
  public static final int XLAT = 38;
  public static final int JNE = 17;
  public static final int JNC = 51;
  public static final int CMP = 14;
  public static final int NOT = 13;
  public static final int AND = 10;
  public static final int Section = 60;
  public static final int SAR = 30;
  public static final int NOP = 39;
  public static final int OR = 11;
  public static final int CALL = 20;
  public static final int INC = 8;
  public static final int MOV = 3;
  public static final int DIV = 7;
  public static final int MOVSW = 26;
  public static final int BSR = 34;
  public static final int NumeroDecimal = 65;
  public static final int LOOP = 46;
  public static final int Parentesis_c = 55;
  public static final int JMP = 15;
  public static final int Parentesis_a = 54;
  public static final int Global = 59;
  public static final int EOF = 0;
  public static final int RETF = 53;
  public static final int TEST = 27;
  public static final int error = 1;
  public static final int BSF = 33;
  public static final int MUL = 6;
  public static final int ADD = 4;
  public static final int MOVSB = 25;
  public static final int ERROR = 67;
  public static final int CLI = 42;
  public static final int Identificador = 61;
  public static final int STOSB = 45;
  public static final int POPF = 36;
  public static final int ROR = 32;
  public static final int DEC = 9;
  public static final int JZ = 18;
  public static final int Numero = 66;
  public static final int ROL = 31;
  public static final int SUB = 5;
  public static final int NumeroBinario = 62;
  public static final int LODSB = 44;
  public static final int HLT = 40;
  public static final int LEA = 24;
}

